Repository AreWeAntiCheatYet/AreWeAntiCheatYet, pull requests merged in 2024-08, with the labels that each got.

#1695 Move Genshin bits around
  games.json
Labels: enhancement, hacktober-approved

#1706 games: BnS uses VIOLET instead of GameGuard
  games.json
  public/anticheats/violet.webp
  src/utils/games.ts
Labels: documentation, enhancement, good first issue, hacktober-approved

#1708 games: Add Splitgate 2
  games.json
Labels: documentation, enhancement, hacktober-approved
